version: '3'
services:
  db:
    image: mysql:8.2.0
    environment:
      #       MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: raynaudAttacks2
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 990709
      MYSQL_ROOT_PASSWORD: 990709
      MYSQL_TCP_PORT: 3306
    ports:
      - "3307:3306"
#    expose:
#      - '3306'
  #    volumes:
  #      - my-db:/var/lib/mysql




  app:
    build: .
    image: app:latest
    restart: always
    #    command: [ "./wait-for-it.sh", "mysql:3306", "--", "your-app-start-command" ]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/raynaudAttacks2?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
    ports:
      - '80:8080'


